### ISSUE TITLE
german infected

### ISSUE THREAD

**Issue by b4dr1ck** [sueswe/myAMC#3]
please use englisch sub names and don't mix german and english in your code.
It's kind of weird.  So fix it, right now!!!

**Comment by sueswe** [comment]
You r absolutely right, bitch! Will be fixed soon!

**Comment by sueswe** [comment]
Fixed.
$ grep '^sub' myAMC.pl
sub get_sub_from_mail {
sub action {
sub action_on_subject {
sub inform_admin {
sub delAll {
sub move_saved_email {
sub saveHeadBody {
sub popconnect {
sub popclose {
sub checkHeaders {
sub timestamp {
sub help {
